### ISSUE TITLE
Investigate Sony Spresense camera and wifi

### ISSUE THREAD

**Issue by TomFranklinUoG** [TeachingMaterial/assignment_1-ace_2022-23#10]
- [x] Investigate how to interface Sony Spresense platform with camera and wifi modules
- [x] Complete test programmes to prove successful implementation of camera module only

**Comment by cybermedhm** [comment]
The Sony Spresense board don't have an Ethernet capabilities integrated. therefore an add-on wi-fi module has to be connected to the board. 
Second the usage of the Camera library and the utilisation of the camera and video options

**Comment by cybermedhm** [comment]
[Wi-fi and camera connectivity.docx](https://github.com/TeachingMaterial/assignment_1-ace_2022-23/files/10548894/Wi-fi.and.camera.connectivity.docx)

**Comment by cybermedhm** [comment]
[Testing camera capabilities of Spresense board. docx](https://github.com/TeachingMaterial/assignment_1-ace_2022-23/files/10669719/Testing.camera.capabilities.of.Spresense.board.docx)
