### ISSUE TITLE
Identify method of data transfer from server to mobile app

### ISSUE THREAD

**Issue by TomFranklinUoG** [TeachingMaterial/assignment_1-ace_2022-23#20]

**Comment by aakashdmathur23** [comment]
Parse the above example file after deserializing it with the json.load( ) function and count the number of lines needed to store the addresses of the students. Store these values in a list along with the person’s name, and print the list.

Algorithm:

Load the json file into a file object and use the json.load() function to deserialize it into a python dictionary. Store this python dictionary in a variable named jsonData.
Loop over all people in jsonData and store their name along with the number of address lines in a variable data. Append data to result.
Print the result.

import json
with open("example.json","r") as file:
    jsonData = json.load(file)
 
result = []
for name in jsonData:
    data = [name, len(jsonData[name]["address"])]
    result.append( data )
print("Person vs Number of Address Lines:")
for name, lines in result:
    print( name + " " + str(lines) )
