### ISSUE TITLE
Generate mobile app

### ISSUE THREAD

**Issue by TomFranklinUoG** [TeachingMaterial/assignment_1-ace_2022-23#22]
- [ ] Develop outline app layout
- [x] Investigate conversion of JSON to BMP within app
- [x] implement web sockets to connect to server
- [x] Prove detection/connection of external devices on Wifi
- [x] Investigate API backup if WebSocket proves unsuccessful

**Comment by Cstratton-brown** [comment]
changed web API to web socket connection after Kingdavids research

**Comment by TomFranklinUoG** [comment]
Task list associated with issue updated to reflect current needs. Added points:

 Prove detection/connection of external devices on Wifi
 Investigate API backup if WebSocket proves unsuccessful

**Comment by Cstratton-brown** [comment]
Conversion of MJPEG to JPEG method created along with connecting to servers via websocket URL to transmit data.

**Comment by Cstratton-brown** [comment]
URLs for websockets are currently hardcoded and cannot be changed in app at this time

**Comment by Cstratton-brown** [comment]
Image transfer from board confirmed with image Display. Code added to transfer to server, receive from server and transfer to display implemented. All that remains is testing those features and creating a nice GUI,
