### ISSUE TITLE
Research MySQL Database for Image storage

### ISSUE THREAD

**Issue by kdadeoye** [TeachingMaterial/assignment_1-ace_2022-23#26]
Goals:

1) Insert binary data into a MySQL table using Python.
2) Read BLOB data files from the MySQL table in Python

**Comment by aakashdmathur23** [comment]
BSON is the format used both for data storage and network transfer in MongoDB. After storing data in MongoDB, you may want to get your data back as JSON, among many other formats. When you want to export your files as JSON, you can use MongoDB's database tool, bsondump , to convert BSON documents to JSON.

**Comment by aakashdmathur23** [comment]
https://pynative.com/python-mysql-blob-insert-retrieve-file-image-as-a-blob-in-mysql/

**Comment by aakashdmathur23** [comment]
Entities to be stored:
1) IDP (ID of the Picture)
2) Timestamp
3) IDG (ID of the glasses)
4) BLOB

**Comment by aakashdmathur23** [comment]
Average Size of an Image : 7.5 KB
so the blob used would be BLOB
