### ISSUE TITLE
Test method of renaming image files captured by camera

### ISSUE THREAD

**Issue by TomFranklinUoG** [TeachingMaterial/assignment_1-ace_2022-23#32]
Naming convention of image on server to be:

YYYYMMDD_HHMMSSMsMsMs_x.bmp

Where:
Y = Year characters
M = Month characters
D = Day characters
H = Hour characters
M = Minute characters
S = Second characters
Ms = Millisecond characters
x = Arbitrary number to identify camera

This is inkeeping with ISO 8601

Images taken by camera are to be renamed immediately when stored on SD card prior to streaming over WiFi

**Comment by Modarrcode** [comment]
Added to js script backend, with:
now.getFullYear()}${(now.getMonth() + 1).toString().padStart(2, '0')}${now.getDate().toString().padStart(2, '0')}${now.getHours().toString().padStart(2, '0')}${now.getMinutes().toString().padStart(2, '0')}${now.getSeconds().toString().padStart(2, '0')}${now.getMilliseconds().toString().padStart(3, '0')}
