### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by CompEng0001** [TeachingMaterial/assignment_1-ace_2022-23#42]
@aakashdmathur23, I have seen little evidence of the databases progression. Can you please address this and get your solution pushed to the origin. 

[Your latest commit](https://github.com/TeachingMaterial/assignment_1-ace_2022-23/blob/9e58bc979783faa23a99cd5e28d40212eb2f390d/Screenshot%202023-02-28%20at%203.14.57%20pm.png) for your reference.

**Comment by aakashdmathur23** [comment]
MySQL Database script created and uploaded using the server on Workbench. Please find the link to the sql file below.

https://github.com/TeachingMaterial/assignment_1-ace_2022-23/blob/7ea9acdea7ff3c2c537420e8ad832489d7a4092b/ACEServer.sql#L1

Currently working on methods to initialize the script created on the server for populating the schema into the database.
