### ISSUE TITLE
Investigate data management of image files using Python

### ISSUE THREAD

**Issue by TomFranklinUoG** [TeachingMaterial/assignment_1-ace_2022-23#5]
Identify an industry-standard method of managing data transfer for image files between devices using Python

**Comment by Modarrcode** [comment]
Would recommend checking out HDF5 file format with Flask as the web interface
https://pypi.org/project/Flask/
https://www.geeksforgeeks.org/hdf5-files-in-python/

**Comment by kdadeoye** [comment]
I have opted to using JSON library for the data managements for the image transfer
