### ISSUE TITLE
Investigate data pull from server using JSON

### ISSUE THREAD

**Issue by TomFranklinUoG** [TeachingMaterial/assignment_1-ace_2022-23#9]
- [x] Can spresense support python
- [ ] Are there libraries for spresense to encode/decode python files
- [ ] Research surround method of requesting image file from server and then using JSON to receive requested file

**Comment by kdadeoye** [comment]
[PYTHON FOR DATA TRANSFER USING JSON.docx](https://github.com/TeachingMaterial/assignment_1-ace_2022-23/files/10536127/PYTHON.FOR.DATA.TRANSFER.USING.JSON.docx)

**Comment by kdadeoye** [comment]
To investigate data pull from a server using JSON, you can follow these steps:
1.	Make an HTTP request to the server using a library such as requests in Python.
2.	Check the status code of the response to see if the request was successful. A status code of 200 means that the request was successful, while a code in the 400s or 500s indicates an error.
3.	If the request was successful, parse the JSON data from the response using the JSON method.
4.	Inspect the contents of the data variable to see what information was received from the server.
5.	Depending on the structure of the data, you may need to perform additional parsing or processing to extract the information needed.
